# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  default: &default
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          command: |
            mkdir -p $PWD/tmp
            echo 'rails_neutrino@rubyonracetracks.com' > $PWD/tmp/git_email.txt
            echo 'Rails Neutrino' > $PWD/tmp/git_name.txt
            gem install rails
  test-v1:
    <<: *default
    steps:
      - checkout
      - run:
          name: rails new
          command: bash v1.sh

workflows:
  version: 2
  tests:
    jobs:
      - test-v1
