jobs:
  default: &default
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout

  test-h2:
    <<: *default
    steps:
      - run:
          name: h2
          command: bash h2.sh

workflows:
  version: 2
  tests:
    jobs:
      - test-h2
