version: 2.1
jobs:
  default: &default
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout

  test0:
    <<: *default
    steps:
      - run:
          name: CircleCI-0
          command: bash circleci0.sh.sh
